
# The name of your website.
name: Engenharia Viva Decora

description:

  # Description of your site. This will show up in google.
  meta: Blog de tecnologia da equipe de Engenharia do Viva Decora com dicas sobre Desenvolvimento de Software

  # Description of your site. This will show up on the front page.
  subtitle: Blog de tecnologia da equipe de Engenharia do Viva Decora com dicas sobre Desenvolvimento de Software

author:
  name: Engenharia Viva Decora

  # Necessary for contact page
  email: devs@vivadecora.com.br

  # Optional text (html) to display after author name. Leave empty if you don't
  # want it.
  info:

url: https://vivadecora.github.io
baseurl: ""

# language attribute in <html> element.
lang: pt-br

# FROM THIS POINT ON EVERYTHING IS OPTIONAL

##############
# APPEREANCE #
##############

# If you want to show the subtitle anywhere else than the front page, use
# {% include subtitle.html %} to include it anywhere you want.
show-subtitle: false
display-social-icons: false

footer-text: Desenvolvido utilizando <a href="https://jekyllrb.com/" title="Jekyll">Jekyll</a> e <a href="https://pages.github.com/" title="GitHub Pages">GitHub Pages</a>, tema <br><a href="http://steinvc.github.io/holo-alfa/" title="Holo Alfa">Holo Alfa</a> por <a href="http://steinvc.github.io/holo-alfa/" title="Stijn">Stijn</a> e escrito pelo time de Engenharia do <a href="https://www.vivadecora.com.br" title="Viva Decora">Viva Decora.

# Preferably 64px in height. Leave empty = disable.
logo-image: # /img/logo.png

# Toolbar color for Chrome on Android.
theme-color-attr: "#00f0ff"

# Color of Microsoft live Tile.
ms-tile-color: "#00f0ff"

# Color used throughout the theme. Format: R, G, B.
theme-color: 205, 49, 40 # Original: 0, 240, 255

# Text color used throughout the theme. Format: R, G, B.
text-color: 0, 0, 0 # Original: 0, 0, 0

# Background color used throughout the theme. Format: R, G, B.
# Note: if you change the background color AND you use cover images, you should
#       also change the CSS gradient in "_includes\gradient.css" to match the
#       background color. Edit and copy it from here:
#       http://www.colorzilla.com/gradient-editor/#ffffff+0,ffffff+100&0+0,1+100
background-color: 255, 255, 255 # Original: 255, 255, 255

display-author-post-page: true
display-author-front-page: true

# http://alanwsmith.com/jekyll-liquid-date-formatting-examples
date_format: "%b %-d, %Y"

# Minimal screen-width after which the navigation will change position from
# vertical to horizontal.
nav-breaking-point: 520px

# Number of posts on each page.
paginate: 5

# Display links for the previous and next post on post pages.
display-next-prev-post: false

# Leave empty if you don't want comments on post pages.
disqus-shortname:


################
# SOCIAL ICONS #
################

# Use a complete url here, including http:// and such. Requiring just usernames
# has been considered, but this is way more customizable.
twitter:
youtube:
instagram: https://www.instagram.com/vivadecora/
tumblr:
facebook: https://www.facebook.com/vivadecora
google-plus: https://plus.google.com/+VivadecoraBrasil/posts
reddit:
soundcloud:
medium:
linkedin: https://www.linkedin.com/company/viva-decora
github: https://www.github.com/vivadecora
behance:
codepen:
dribbble:
trello:
stack-overflow:
bitcoin:
paypal:


#####################
# CUSTOMIZABLE TEXT #
#####################

# Useful for translating into other languages.

var_on_the_web: On the web
var_read: Continuar a leitura...
var_newer: Novos
var_older: Antigos
var_next_post: Próximo
var_previous_post: Anterior
var_less_than_a_minute_read: < 1 min de leitura
var_min_read: min de leitura # Text after reading time. Example: 5 min read.
var_post_by: Escrito por
var_guest_post_by: Escrito por
var_your_email: Seu email
var_your_message: Sua mensagem


##################
# BUILD SETTINGS #
##################

# You don't have to change these.

exclude: [vendor]
highlighter: rouge
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: none
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"
